from datetime import timedelta

import pytest
from django.utils import timezone

from donors.models import VirtualDonorCard


@pytest.mark.django_db
def test_donor_is_eligible_without_previous_donation(donor_profile):
    assert donor_profile.is_eligible_to_donate() is True
    assert donor_profile.days_until_eligible() == 0
    assert donor_profile.get_next_eligible_date() is None


@pytest.mark.django_db
def test_donor_not_eligible_before_90_days(donor_profile):
    donor_profile.last_donation_date = timezone.localdate() - timedelta(days=30)
    assert donor_profile.is_eligible_to_donate() is False
    assert donor_profile.days_until_eligible() == 60


@pytest.mark.django_db
def test_donor_eligible_at_90_days(donor_profile):
    donor_profile.last_donation_date = timezone.localdate() - timedelta(days=90)
    assert donor_profile.is_eligible_to_donate() is True


@pytest.mark.django_db
def test_virtual_card_computed_properties(donor_profile):
    donor_profile.total_donations = 3
    donor_profile.total_volume_ml = 1350
    donor_profile.save()
    card = donor_profile.virtual_card
    assert card.card_number.startswith("BDEN-YAO-")
    assert card.is_regular_donor is True
    assert card.total_volume_ml == 1350
    assert card.blood_type == donor_profile.blood_type


@pytest.mark.django_db
def test_card_number_autogenerated(donor_profile):
    card = VirtualDonorCard.objects.get(donor_profile=donor_profile)
    assert card.card_number
