# Generated by Django 4.2.13 on 2026-05-29 22:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("EMERGENCY", "Emergency Request"),
                            ("CAMPAIGN", "Campaign"),
                            ("SYSTEM", "System"),
                        ],
                        default="SYSTEM",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("read", models.BooleanField(default=False)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "read"],
                        name="notificatio_user_id_1f75db_idx",
                    ),
                    models.Index(
                        fields=["user_id", "type"],
                        name="notificatio_user_id_6b5847_idx",
                    ),
                ],
            },
        ),
    ]
