# Generated by Codex on 2026-05-30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("EMERGENCY", "Emergency Request"),
                    ("CAMPAIGN", "Campaign"),
                    ("SYSTEM", "System"),
                    ("REMINDER", "Reminder"),
                ],
                default="SYSTEM",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="email_status",
            field=models.CharField(default="PENDING", max_length=16),
        ),
        migrations.AddField(
            model_name="notification",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.UUIDField(db_index=True, unique=True)),
                ("emergency_push", models.BooleanField(default=True)),
                ("emergency_email", models.BooleanField(default=True)),
                ("campaign_push", models.BooleanField(default=True)),
                ("campaign_email", models.BooleanField(default=False)),
                ("system_push", models.BooleanField(default=True)),
                ("system_email", models.BooleanField(default=False)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notification_preferences",
            },
        ),
    ]
