# Generated by Django 4.2.13 on 2026-05-29 21:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BloodRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hospital_id", models.UUIDField(db_index=True)),
                ("hospital_name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("blood_type", models.CharField(max_length=3)),
                ("units_needed", models.PositiveIntegerField(default=1)),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="HIGH",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("MATCHED", "Matched"),
                            ("FULFILLED", "Fulfilled"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "blood_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequestResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("donor_id", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                            ("UNAVAILABLE", "Unavailable"),
                        ],
                        default="ACCEPTED",
                        max_length=12,
                    ),
                ),
                ("responded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="blood_requests.bloodrequest",
                    ),
                ),
            ],
            options={
                "db_table": "request_responses",
            },
        ),
        migrations.AddIndex(
            model_name="bloodrequest",
            index=models.Index(
                fields=["status", "city"], name="blood_reque_status_21e49d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bloodrequest",
            index=models.Index(
                fields=["blood_type", "city"], name="blood_reque_blood_t_530e07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bloodrequest",
            index=models.Index(
                fields=["hospital_id"], name="blood_reque_hospita_77128a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="requestresponse",
            index=models.Index(
                fields=["request", "status"], name="request_res_request_234940_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="requestresponse",
            unique_together={("request", "donor_id")},
        ),
    ]
