# Generated by Codex on 2026-05-30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("blood_requests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("OPEN", "Open"),
                    ("MATCHED", "Matched"),
                    ("PARTIALLY_FULFILLED", "Partially fulfilled"),
                    ("FULFILLED", "Fulfilled"),
                    ("EXPIRED", "Expired"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="ACTIVE",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="latitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="longitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="cancellation_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="requestresponse",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("DECLINED", "Declined"),
                    ("NO_RESPONSE", "No response"),
                    ("UNAVAILABLE", "Unavailable"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="requestresponse",
            name="donor_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="requestresponse",
            name="donor_blood_type",
            field=models.CharField(blank=True, default="", max_length=3),
        ),
        migrations.AddField(
            model_name="requestresponse",
            name="donor_phone",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="requestresponse",
            name="distance_km",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.CreateModel(
            name="MatchingResult",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("donor_id", models.UUIDField(db_index=True)),
                ("distance_km", models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ("compatibility_score", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matching_results",
                        to="blood_requests.bloodrequest",
                    ),
                ),
            ],
            options={
                "db_table": "request_matching_results",
                "ordering": ["distance_km", "-compatibility_score"],
            },
        ),
        migrations.AddIndex(
            model_name="matchingresult",
            index=models.Index(fields=["request", "compatibility_score"], name="request_mat_request_95ca22_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="matchingresult",
            unique_together={("request", "donor_id")},
        ),
    ]
