# Generated by Codex for BDEN campaign-service MVP.
import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DonationCampaign",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("hospital_user_id", models.UUIDField(db_index=True)),
                ("hospital_name", models.CharField(max_length=255)),
                ("hospital_email", models.EmailField(blank=True, default="", max_length=254)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("blood_types_needed", models.JSONField(blank=True, default=list)),
                ("target_donors", models.PositiveIntegerField(blank=True, null=True)),
                ("target_volume_ml", models.PositiveIntegerField(blank=True, null=True)),
                ("donor_incentives", models.TextField(blank=True, default="")),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("city", models.CharField(max_length=100)),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("status", models.CharField(choices=[("PENDING", "Pending Review"), ("APPROVED", "Approved"), ("ONGOING", "Ongoing"), ("COMPLETED", "Completed"), ("REJECTED", "Rejected"), ("CANCELLED", "Cancelled")], db_index=True, default="PENDING", max_length=12)),
                ("rejection_reason", models.CharField(blank=True, default="", max_length=500)),
                ("approved_by", models.UUIDField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("actual_donors", models.PositiveIntegerField(default=0)),
                ("actual_volume_ml", models.PositiveIntegerField(default=0)),
                ("interested_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "donation_campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignInterest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("donor_user_id", models.UUIDField(db_index=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("campaign", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="interests", to="campaigns.donationcampaign")),
            ],
            options={
                "db_table": "campaign_interests",
                "unique_together": {("campaign", "donor_user_id")},
            },
        ),
        migrations.AddIndex(model_name="donationcampaign", index=models.Index(fields=["hospital_user_id"], name="donation_ca_hospita_e63f4c_idx")),
        migrations.AddIndex(model_name="donationcampaign", index=models.Index(fields=["status", "start_datetime"], name="donation_ca_status_9d8a2d_idx")),
        migrations.AddIndex(model_name="donationcampaign", index=models.Index(fields=["city", "status"], name="donation_ca_city_e4d7f4_idx")),
    ]
