# Generated by Codex for BDEN campaign-service MVP.
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MythArticle",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("myth_statement", models.CharField(max_length=500)),
                ("truth_statement", models.TextField()),
                ("source", models.CharField(blank=True, default="", max_length=255)),
                ("category", models.CharField(choices=[("HEALTH", "Health"), ("RELIGIOUS", "Religious"), ("CULTURAL", "Cultural"), ("PROCEDURAL", "Procedural"), ("ELIGIBILITY", "Eligibility")], db_index=True, max_length=15)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("created_by", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "myth_articles",
                "ordering": ["category", "title"],
            },
        ),
        migrations.AddIndex(model_name="mytharticle", index=models.Index(fields=["category", "is_published"], name="myth_articl_categor_64a0dc_idx")),
    ]
